### ISSUE TITLE
Latte doesn't launch with Unity or Cupertino layout

### ISSUE THREAD

**Issue by Anonymo** [feren-OS/Bug-Reporting-Center#82] opened 2019-12-27 22:16 UTC
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___

System Settings > Global Theme

**Describe the bug**

Desktop layout is supposed to change to Unity look or Cupertino Look but latte-dock does not appear to launch.

**Steps to Reproduce**
1. Go to System Settings
2. Go to Global Theme
3. Try to change to Unity layout
4. Apply

**Expected behavior**

![lattedockmissing](https://user-images.githubusercontent.com/967787/71534393-32405780-28c4-11ea-83e3-3a45f2634c30.png)

**Screenshots**

**Additional context**

**Comment by feren** [comment] 2019-12-28 15:39
feren-latte-launch should not be run as Superuser.
Run the following commands and then make sure you run feren-latte-launch as the normal user (No sudo):
```
sudo killall feren-latte-launch latte-dock
sudo rm -rf /home/meow/.config/latte /home/meow/.config/lattedockrc /tmp/latte-dock.meow.lock
cp -rf /etc/skel/.config/latte /home/meow/.config/lattedockrc
cp -f /etc/xdg/lattedockrc /home/meow/.config/lattedockrc
sudo apt update
sudo apt install -y feren-latte-config
cd /tmp
nohup feren-latte-launch &
```

Now close the Terminal window.

**Comment by Anonymo** [comment] 2019-12-30 04:29
Tried several times, didn't fix it.

**Comment by feren** [comment] 2019-12-30 17:47
Have you fully updated everything?

**Comment by Anonymo** [comment] 2019-12-30 17:58
> Have you fully updated everything and then logged out and back in?

Yes, I am fully up to date on the distro.  Have restarted several times.

**Comment by feren** [comment] 2019-12-30 18:01
Is there any logs if you do `feren-latte-launch quit; latte-dock --replace`?

**Comment by Anonymo** [comment] 2019-12-30 18:16
I think I only this get:

Dec 30 12:07:06 batmobile nm-dispatcher[28358]: req:1 'dhcp4-change' [wlp1s0]: new request (2 scripts)
Dec 30 12:07:06 batmobile nm-dispatcher[28358]: req:1 'dhcp4-change' [wlp1s0]: start running ordered scripts...
Dec 30 12:09:25 batmobile rtkit-daemon[2653]: Successfully made thread 32063 of process 2571 (n/a) owned by '1000' RT at priority 10.
Dec 30 12:09:55 batmobile systemd[1]: Stopping System Logging Service...
Dec 30 12:09:55 batmobile rsyslogd[769]:  [origin software="rsyslogd" swVersion="8.32.0" x-pid="769" x-info="http://www.rsyslog.com"] exiting on signal 15.
Dec 30 12:09:55 batmobile systemd[1]: Stopped System Logging Service.
Dec 30 12:09:55 batmobile systemd[1]: Closed Syslog Socket.
Dec 30 12:09:55 batmobile systemd[1]: Reloading.
Dec 30 12:09:55 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-plasma-startup-adjuster.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:55 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-autopackagemgmt.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:55 batmobile systemd[1]: Reloading.
Dec 30 12:09:55 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-plasma-startup-adjuster.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:55 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-autopackagemgmt.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:55 batmobile systemd[1]: Reloading.
Dec 30 12:09:55 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-plasma-startup-adjuster.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:55 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-autopackagemgmt.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:58 batmobile systemd[1]: Reloading.
Dec 30 12:09:58 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-plasma-startup-adjuster.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:58 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-autopackagemgmt.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:59 batmobile systemd[1]: Reloading.
Dec 30 12:09:59 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-plasma-startup-adjuster.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:59 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-autopackagemgmt.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:59 batmobile systemd[1]: Reloading.
Dec 30 12:09:59 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-plasma-startup-adjuster.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:59 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-autopackagemgmt.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:59 batmobile systemd[1]: Starting System Logger Daemon...
Dec 30 12:09:59 batmobile systemd[1]: Started System Logger Daemon.
Dec 30 12:09:59 batmobile systemd[1]: Reloading.
Dec 30 12:09:59 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-plasma-startup-adjuster.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:09:59 batmobile systemd[1]: Configuration file /etc/systemd/system/feren-autopackagemgmt.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 30 12:10:58 batmobile systemd-resolved[651]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Dec 30 12:13:52 batmobile kernel: kquitapp5[8579]: segfault at 4 ip 00007fc3594fac36 sp 00007fff76895b50 error 4 in libQt5Core.so.5.13.2[7fc3593ba000+53c000]
Dec 30 12:13:52 batmobile kernel: Code: 00 00 00 00 48 8d 41 14 0f 1f 40 00 48 39 c3 0f 84 bf fe ff ff 4c 29 d0 31 d2 48 c1 f8 02 49 8b 04 c3 48 85 c0 74 08 48 8b 10 <8b> 52 04 01 d6 49 89 00 41 c7 40 08 00 00 00 00 41 89 50 0c e9 95
Dec 30 12:13:52 batmobile dbus-daemon[2377]: [session uid=1000 pid=2377] Connection :1.170 (uid=1000 pid=8622 comm="dbus-monitor type='method_call',destination='org.k" label="unconfined") became a monitor.
Dec 30 12:13:52 batmobile kernel: kquitapp5[8579]: segfault at 4 ip 00007fc3594fac36 sp 00007fff76895b50 error 4 in libQt5Core.so.5.13.2[7fc3593ba000+53c000]
Dec 30 12:13:52 batmobile kernel: Code: 00 00 00 00 48 8d 41 14 0f 1f 40 00 48 39 c3 0f 84 bf fe ff ff 4c 29 d0 31 d2 48 c1 f8 02 49 8b 04 c3 48 85 c0 74 08 48 8b 10 <8b> 52 04 01 d6 49 89 00 41 c7 40 08 00 00 00 00 41 89 50 0c e9 95
Dec 30 12:13:52 batmobile dbus-daemon[2377]: [session uid=1000 pid=2377] Connection :1.170 (uid=1000 pid=8622 comm="dbus-monitor type='method_call',destination='org.k" label="unconfined") became a monitor.
Dec 30 12:13:55 batmobile xdg-desktop-por[19341]: Cannot transform xsetting gtk-button-images of type gchararray to type gboolean

Dec 30 12:13:55 batmobile xdg-desktop-por[19341]: Cannot transform xsetting gtk-button-images of type gchararray to type gboolean

Dec 30 12:13:55 batmobile xdg-desktop-por[19341]: Cannot transform xsetting gtk-menu-images of type gchararray to type gboolean

Dec 30 12:13:55 batmobile xdg-desktop-por[19341]: Cannot transform xsetting gtk-menu-images of type gchararray to type gboolean

**Comment by feren** [comment] 2019-12-30 18:57
That doesn't look like logs for `latte-dock --replace`.

**Comment by Anonymo** [comment] 2019-12-31 16:27
Where is the log location for what I need?

**Comment by feren** [comment] 2019-12-31 17:40
The output of `feren-latte-launch quit; latte-dock --replace`

**Comment by Anonymo** [comment] 2019-12-31 21:02
$ feren-latte-launch quit; latte-dock --replace
Exiting...

Terminated

**Comment by feren** [comment] 2020-01-01 14:22
Oops, it must've launched latte-dock --replace too soon.

Try `latte-dock --replace` after the "Terminated".

**Comment by Anonymo** [comment] 2020-01-01 15:44
![image](https://user-images.githubusercontent.com/967787/71643161-5791e480-2c7b-11ea-8e74-2402b53c0093.png)

**Comment by feren** [comment] 2020-01-01 16:04
alright then... can you upload ~/.config/lattedockrc here as well as ~/.config/latte/Ubuntu Unity.layout.latte ?

**Comment by Anonymo** [comment] 2020-01-02 16:07
[Ubuntu Unity.layout.latte.zip](https://github.com/feren-OS/Bug-Reporting-Center/files/4016464/Ubuntu.Unity.layout.latte.zip)

![image](https://user-images.githubusercontent.com/967787/71677083-7a89ca80-2d47-11ea-857b-4fbe3ef892bf.png)

so that might be the issue, I don't have a ~./config/lattedockrc

**Comment by Anonymo** [comment] 2020-01-02 16:59
ah I see, lattedockrc is a folder.  Sorry.

[lattedockrc.zip](https://github.com/feren-OS/Bug-Reporting-Center/files/4016628/lattedockrc.zip)

**Comment by feren** [comment] 2020-01-02 17:05
?
![image](https://user-images.githubusercontent.com/11057934/71680447-07517a00-2d82-11ea-8307-107baf8d48c0.png)

**Comment by Anonymo** [comment] 2020-01-02 17:08
> ?
> ![image](https://user-images.githubusercontent.com/11057934/71680447-07517a00-2d82-11ea-8307-107baf8d48c0.png)

Yeah I don't have that file.

**Comment by feren** [comment] 2020-01-02 17:10
What's the permissions like on the .config folder?

**Comment by Anonymo** [comment] 2020-01-02 17:11
> What's the permissions like on the .config folder?

![image](https://user-images.githubusercontent.com/967787/71680803-a9f10500-2d50-11ea-8289-380955b01dbb.png)

**Comment by feren** [comment] 2020-01-02 17:13
Try `sudo chmod 755 -R /home/meow.config`

**Comment by feren** [comment] 2020-01-02 17:13
*meow/.config

**Comment by feren** [comment] 2020-01-02 17:14
As for otherwise since I can't seem to reproduce this issue I'll mark it as Non-producable

**Comment by Anonymo** [comment] 2020-01-02 17:18
> As for otherwise since I can't seem to reproduce this issue I'll mark it as Non-producable

That's cool.  I might try a reinstall when I get a chance.  I don't know what happened.  It worked fine when I installed from release candidate 2 and throghout all that.  Then I started over and reinstalled with the final release and it didn't work.

**Comment by feren** [comment] 2020-01-02 17:18
![Screenshot_20200102_171833](https://user-images.githubusercontent.com/11057934/71681196-f30e7c80-2d83-11ea-8e04-d4fffac2bad6.png)

**Comment by Anonymo** [comment] 2020-01-02 17:20
> ![Screenshot_20200102_171833](https://user-images.githubusercontent.com/11057934/71681196-f30e7c80-2d83-11ea-8e04-d4fffac2bad6.png)

Yes, this is what is showing on mine after running that command you posted.

**Comment by Anonymo** [comment] 2020-01-02 17:21
Can you send me your lattedockrc file and I'll place it in mine?

**Comment by feren** [comment] 2020-01-02 17:22
Try deleting the lattedockrc folder/file and running latte-dock --replace again.

**Comment by feren** [comment] 2020-01-02 17:23
My file was auto-generated by Latte.

**Comment by Anonymo** [comment] 2020-01-02 17:28
Didn't work.  I'll try reinstalling later.  This is actually the main feature that got me hooked on your distro.  I actually was running Arch with the same Unity configuration with latte dock and yours is much better looking and easier to setup than mine.  I'll let you know how it goes when I do it.  Thanks for the support.

**Comment by Anonymo** [comment] 2020-01-02 17:33
The only thing I can think of that I did different when I installed the final vs the release candidate 2 is that with RC2, I let the partitioner clear everything in the installer vs when I installed the final, I had seperate partitions from my Arch install with 4 partitions.  ESP, swap,root and home because I had some stuff stored on my home that I wanted to keep.  But I deleted all the hidden folders and .files in home before installing and don't know if something along the way got messed up because I didn't create a fresh home.

**Comment by feren** [comment] 2020-01-02 17:34
Try `sudo chown -hR meow:meow /home/meow && sudo chmod 755 /home/meow/.config /home/meow/.local /home/meow/.cache`

**Comment by Anonymo** [comment] 2020-01-02 17:48
> Try `sudo chown -hR meow:meow /home/meow && sudo chmod -R 755 /home/meow/.config /home/meow/.local /home/meow/.cache`

I tried this, and it did something different.  Top dock is fully working but side dock is not showing up.

So I tried the steps you had me do at the beginning.

sudo killall feren-latte-launch latte-dock
sudo apt update
sudo apt install -y feren-latte-config
sudo rm -rf /home/meow/.config/latte /home/meow/.config/lattedockrc /tmp/latte-dock.meow.lock
cp -rf /etc/skel/.config/latte /home/meow/.config/lattedockrc
cp -f /etc/xdg/lattedockrc /home/meow/.config/lattedockrc
cd /tmp
nohup feren-latte-launch &

But still only top dock is showing

![image](https://user-images.githubusercontent.com/967787/71682601-cf344200-2d55-11ea-9ec0-6c1bd632f0ba.png)

**Comment by feren** [comment] 2020-01-02 17:52
It's reset to default Latte settings. Right-click it, Layouts, Ubuntu Unity.

**Comment by feren** [comment] 2020-01-02 17:53
Closing and marking as User Error as it was just a permissions issue from using a home folder from another OS

**Closed by feren** 2020-01-02 17:52 UTC
Labels: Non-producable

**Comment by Anonymo** [comment] 2020-01-02 17:55
the top panel is just a normal panel, not latte, so can't right click it and show those options.

**Comment by feren** [comment] 2020-01-02 17:55
The dock...

**Comment by feren** [comment] 2020-01-02 17:56
It'd probably be easier to just re-apply Ubuntu Unity Layout.

**Comment by Anonymo** [comment] 2020-01-02 19:40
So I just went ahead and did a reinstall by backing up and formatting the home partition this time and all is well again.  Thank you for all the time you spent on trying to get me going.  I am loving this OS because you do all the tweaks I usually do on KDE, like turning off wallet, the Unity Desktop, the 40s systemd timer and many others.  I appreciate all your hard work and attention to details.
