### ISSUE TITLE
Changing Feren OS language to Spanish, latte-dock does not start

### ISSUE THREAD

**Issue by frlezcano** [feren-OS/Bug-Reporting-Center#74] opened 2019-12-26 12:00 UTC
**Package Name or Section of Feren OS where this bug resides**
/usr/bin/feren-latte-launch

**Describe the bug**
Setting a global theme that uses latte-dock, it doesn't star

**Steps to Reproduce**
1. Change Language to spanish
2. Change Global Theme to Cupertino Layout

**Expected behavior**
I hope to start latte-dock as part of the applied global theme

**Screenshots**

**Additional context**
/usr/bin/feren-latte-launch

line 18
while ! wmctrl -l | grep -q "Desktop — Plasma"; do

rlezcano@TQX775:~$ wmctrl -l
0x02400122 -1 TQX775 Escritorio — Plasma
0x02400128 -1 TQX775 Escritorio — Plasma
0x03a00007  0 TQX775 - : nano — Konsole
0x02400144 -1 TQX775 Plasma
0x03c00102  0 TQX775 Carpeta personal
0x04200017  0 TQX775 Tema global — Módulo de preferencias del sistema
0x04400007  0 TQX775 - : nano — Konsole
0x04600007  0 TQX775 rlezcano : bash — Konsole

temporary solution:
while ! wmctrl -l | grep -q "Escritorio — Plasma"; do

**Comment by feren** [comment] 2019-12-26 15:20
This is a duplicate of #72 and has been fixed.

**Closed by feren** 2019-12-26 15:20 UTC
