### ISSUE TITLE
Stacer 1.1 not found

### ISSUE THREAD

**Issue by zaivala** [feren-OS/Bug-Reporting-Center#36] opened 2019-06-25 14:05 UTC
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___
Desktop
**Describe the bug**
Stacer 1.0.7 displays fine. When I update to Stacer 1.1.0, feren shows no errors but then cannot find Stacer.
**Steps to Reproduce**
1. Install Stacer 1.0.7
2. Download upgrade to 1.1.0
3. Install using gdebi
4. Check menu for Stacer

**Expected behavior**

I expect to be able to open and use Stacer.
**Screenshots**

**Additional context**

**Comment by feren** [comment] 2019-06-25 19:13
Reporter confirmed externally that this was just an issue caused by an external repository not included in Feren OS, closing...

**Closed by feren** 2019-06-25 19:13 UTC
Labels: Confirmed, Upstream
