### ISSUE TITLE
apps not installing from store

### ISSUE THREAD

**Issue by coolvan** [feren-OS/Bug-Reporting-Center#182] opened 2020-12-13 22:55 UTC
**Package Name or Section of Feren OS where this bug resides**
Where does this bug happen? (e.g.: feren-themer-cinnamon) ___Feren App store

**Describe the bug**
tried to install BOINC.  The completion bar gets about 80% done then hangs. I have left it for over 24 hours without terminating. With system reboot, no change.  Other app installs are similar, though I had one that hung, and when I killed the store and brought it back up to try again, it had a LAUNCH button.

**Steps to Reproduce**
1. download any app from the Store

**Expected behavior**

**Screenshots**

**Additional context**

This is a totally new install, on a new hard drive

Intel i5 system, HP hardware.  12 GB ram
Feren OS 2020.11
Kernel 5.4.0-58
plasma ver 5.20.4
frameworks 5.76.0

**Comment by dominichayesferen** [comment] 2020-12-14 22:23
Can't say I've been able to reproduce this one except for extremely rare cases, and those rare cases have given me little to no useful information on what is going wrong.

**Comment by coolvan** [comment] 2020-12-20 05:14
hmmm  well maybe I will do a clean install. again. or go back to the previous release- before 2020.11

**Comment by periwinkleFTW** [comment] 2020-12-26 23:58
I had similar problem, some apps would install, others would just freeze. System update did not work either

**Comment by dominichayesferen** [comment] 2020-12-28 17:24
> I had similar problem, some apps would install, others would just freeze. System update did not work either

Your case might just be a different bug which can be fixed by following https://medium.com/feren-os/plasma-workspace-issue-fix-and-fix-methods-for-those-affected-36f3ddd81e96 or reinstalling, if you can't just get Update Manager to successfully update the system on a second attempt.

**Comment by bongo-x** [comment] 2021-01-04 04:48
I had this issue for a couple of days, seems to have fixed itself in the last 24 hours.

**Comment by showson1** [comment] 2021-01-22 02:14
I installed Feren yesterday and have had this problem with three different apps (so far):
Steam
GIMP
OpenVPN daemon

**Comment by dominichayesferen** [comment] 2021-01-23 17:23
gonna investigate this when I have the chance... haven't really seen it happen over here thus far for the most part.

**Comment by coolvan** [comment] 2021-02-11 17:01
Dominic,
 this is an update:
 I did a completely clean install of FerenOS with the 18.04.1 LTS kernel this past weekend. I began with a newly partitioned drive. and I still have the following issues:
 1. installs from the store do not complete, they get 3/5 to 3/4 done then hang with  APTD taking one of my CPUs to 100%  forever. ( until I kill the process)
 2. my USB 3.0 port doesn't work. when I try to boot an external drive on that I/F it works enough to see grub,  then after the kernel begins to load, goes into a loop saying no drives present.  while Feren is running,  LSUSB shows only  USB 2 ports, no USB 3.  and the USB3 is dead, not running as  USB2
 3.  from the terminal 7 ( graphics screen,) I cannot mount drives. I can do it from CLI with sudo
 this is an AMD  system:
[code]
System:    Kernel: 5.8.0-43-generic x86_64 bits: 64 compiler: N/A Desktop: KDE Plasma 5.20.5 
           tk: Qt 5.15.2 wm: kwin_x11 dm: LightDM Distro: Feren OS 20.04 2021.01 
Machine:   Type: Desktop System: Gigabyte product: N/A v: N/A serial: <filter> Chassis: type: 3 
           serial: <filter> 
           Mobo: Gigabyte model: 970A-D3P v: x.x serial: <filter> UEFI: American Megatrends v: FD 
           date: 02/26/2016 
Battery:   Device-1: hidpp_battery_0 model: Logitech M705 serial: <filter> charge: 90% 
           status: Discharging 
CPU:       Topology: 8-Core model: AMD FX-8320E bits: 64 type: MCP arch: Bulldozer 
           L2 cache: 2048 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 51431 
           Speed: 3652 MHz min/max: 1400/3200 MHz Core speeds (MHz): 1: 3639 2: 3522 3: 1797 
           4: 1766 5: 3639 6: 3532 7: 1407 8: 1407 
Graphics:  Device-1: AMD Redwood XT [Radeon HD 5670/5690/5730] vendor: Micro-Star MSI 
           driver: radeon v: kernel bus ID: 01:00.0 chip ID: 1002:68d8 
           Display: x11 server: X.Org 1.20.9 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           compositor: kwin_x11 resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: AMD REDWOOD (DRM 2.50.0 / 5.8.0-43-generic LLVM 11.0.0) 
           v: 3.3 Mesa 20.2.6 compat-v: 3.1 direct render: Yes 
Audio:     Device-1: AMD SBx00 Azalia vendor: Gigabyte driver: snd_hda_intel v: kernel 
           bus ID: 00:14.2 chip ID: 1002:4383 
           Device-2: AMD Redwood HDMI Audio [Radeon HD 5000 Series] vendor: Micro-Star MSI 
           driver: snd_hda_intel v: kernel bus ID: 01:00.1 chip ID: 1002:aa60 
           Device-3: Sunplus Innovation type: USB driver: snd-usb-audio,uvcvideo bus ID: 2-4.3:3 
           chip ID: 1bcf:2284 
           Sound Server: ALSA v: k5.8.0-43-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Gigabyte 
           driver: r8169 v: kernel port: d000 bus ID: 03:00.0 chip ID: 10ec:8168 
           IF: enp3s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 3.43 TiB used: 1.31 TiB (38.0%) 
           ID-1: /dev/sde model: SATA SSD size: 223.57 GiB speed: 6.0 Gb/s serial: <filter> 
           ID-2: /dev/sdf vendor: Seagate model: SSD size: 465.76 GiB speed: 6.0 Gb/s 
           serial: <filter> 
           ID-3: /dev/sdg vendor: Western Digital model: WD1002FAEX-00Y9A0 size: 931.51 GiB 
           speed: 6.0 Gb/s serial: <filter> 
           ID-4: /dev/sdh vendor: Seagate model: ST1000DX001-1NS162 size: 931.51 GiB 
           speed: 6.0 Gb/s serial: <filter> 
           ID-5: /dev/sdi vendor: Western Digital model: WD10EZEX-08M2NA0 size: 931.51 GiB 
           speed: 6.0 Gb/s serial: <filter> 
           ID-6: /dev/sdj type: USB vendor: Kingston model: DataTraveler 3.0 size: 28.90 GiB 
           serial: <filter> 
Partition: ID-1: / size: 206.12 GiB used: 19.87 GiB (9.6%) fs: ext4 dev: /dev/sde2 
           ID-2: swap-1 size: 7.81 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sde3 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 5 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 1-5:2 info: Alcor Micro AU6477 Card Reader Controller type: Mass Storage,HID 
           driver: hid-generic,usb-storage,usbhid rev: 2.0 chip ID: 058f:6364 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 5 rev: 2.0 chip ID: 1d6b:0002 
           Device-2: 2-1:5 info: Kingston DataTraveler 100 G3/G4/SE9 G2 type: Mass Storage 
           driver: usb-storage rev: 2.1 chip ID: 0951:1666 
           Hub: 2-4:2 info: Genesys Logic USB 2.0 Hub ports: 4 rev: 2.0 chip ID: 05e3:0605 
           Device-3: 2-4.3:3 info: Sunplus Innovation type: Video,Audio 
           driver: snd-usb-audio,uvcvideo rev: 2.0 chip ID: 1bcf:2284 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 4 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 5 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 5-0:1 info: Full speed (or root) Hub ports: 5 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 6-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 7-0:1 info: Full speed (or root) Hub ports: 4 rev: 1.1 chip ID: 1d6b:0001 
           Device-4: 7-4:2 info: Logitech Unifying Receiver type: Keyboard,Mouse,HID 
           driver: logitech-djreceiver,usbhid rev: 2.0 chip ID: 046d:c52b 
Sensors:   System Temperatures: cpu: 25.9 C mobo: N/A gpu: radeon temp: 46 C 
           Fan Speeds (RPM): N/A 
Repos:     Active apt repos in: /etc/apt/sources.list 
           1: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           2: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           4: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           5: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb https: //dl.winehq.org/wine-builds/ubuntu/ focal main
           Active apt repos in: /etc/apt/sources.list.d/feren-os-neon.list 
           1: deb [arch=amd64] https: //gitlab.com/feren-os/feren-repositories-neon-focal/raw/master stable neon-focal
           Active apt repos in: /etc/apt/sources.list.d/feren-os.list 
           1: deb https: //gitlab.com/feren-os/feren-repositories-focal/raw/master stable main software
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           No active apt repos in: /etc/apt/sources.list.d/graphics-drivers-ppa-focal.list 
           Active apt repos in: /etc/apt/sources.list.d/opera-stable.list 
           1: deb https: //deb.opera.com/opera-stable/ stable non-free
           Active apt repos in: /etc/apt/sources.list.d/vivaldi.list 
           1: deb http: //repo.vivaldi.com/stable/deb/ stable main
Info:      Processes: 271 Uptime: 1d 16h 43m Memory: 11.73 GiB used: 1.84 GiB (15.7%) 
           Init: systemd v: 245 runlevel: 5 target: graphical.target Compilers: gcc: 9.3.0 alt: 9 
           Client: Unknown python3.8 client inxi: 3.0.38 
[/code]

**Comment by coolvan** [comment] 2021-02-12 20:10
update#2
I set up a different distro on another drive connected to this system. It has the same problem with the USB3.0 ports.  So after reading through some problem reports all across the linux world, I realized that it was a problem with Linux and this particular  family of mother boards.  One of the most popular suggestions was to turn off IOMMU in the BIOS.  I did and voila!  now I have USB 3 ports.  but... BOOOO! I no longer have USB 2.0 ports. WHAT THE HELL?!?!?!  why can Windows get it right, but not Linux?
some people suggest editing the grub parms file to make IOMMU a "soft" on. 

what is a suitable replacement for GEDIT?

**Comment by dominichayesferen** [comment] 2021-02-13 15:32
Does the newest Store update fix the issue for anyone?

**Comment by dominichayesferen** [comment] 2021-02-14 14:31
@coolvan @periwinkleFTW @showson1 @showson1 @bongo-x :point_up:

**Comment by bongo-x** [comment] 2021-02-14 19:59
> Does the newest Store update fix the issue for anyone?

Yes, everything works quickly and correctly now.

**Comment by dominichayesferen** [comment] 2021-02-14 23:45
guess I'll wait for one more confirmation before marking this as FIXED.

**Comment by coolvan** [comment] 2021-02-15 03:13
YES!!!   I had to reboot, because installs were still hanging.  but then I
was able to install Wine, Gparted, some other apps.   Thanks Dominic!
 going skating on the Thames?

**Closed** 2021-02-16 01:58 UTC
Labels: Fixed

**Comment by dominichayesferen** [comment] 2021-11-26 16:04
moving to #223 because activity
