### ISSUE TITLE
failed installation of wine-duo-feren

### ISSUE THREAD

**Issue by billK178** [feren-OS/Bug-Reporting-Center#2] opened 2019-04-23 03:43 UTC
**Package Name or Section of Feren OS where this bug resides**

trying to install wine and play on linux from welcome screen

**Describe the bug**

**Steps to Reproduce**
1. open features in welcome screen, install play on linux and wine

**Expected behavior**
installation on wine and play on linux

**Screenshots**

error message on top right
![Screenshot from 2019-04-22 17-38-45](https://user-images.githubusercontent.com/49892701/56552113-eca5e080-6525-11e9-93bf-2a84704b8a8a.png)

**Additional context**

**Comment by feren** [comment] 2019-04-25 20:46
This is a duplicate of https://github.com/feren-OS/Dependency-Issue-Reporting/issues/1 and has now been fixed in a newly uploaded 64-Bit ISO Update.

To fix this in your Feren OS Installation, go into Software Sources > Maintenance > Downgrade Foreign Packages and look for and downgrade a package called 'libblkid1'. Once you've downgraded this package, Wine will install successfully.

**Closed** 2019-04-25 20:46 UTC
Labels: Duplicate, Fixed
