### ISSUE TITLE
Global Themes on System Setting cannot be installed on 'Get New Global Themes': Message error prompts

### ISSUE THREAD

**Issue by Ciezo** [feren-OS/Bug-Reporting-Center#170] opened 2020-11-05 16:35 UTC
**Package Name or Section of Feren OS where this bug resides**
On system settings > Global Themes > Get New Global Themes 

**Describe the bug**
I was trying to install a new global theme, particularly the BigSur Mac OS Dark. When the download has been finished, a message error prompts and cannot be installed nor it was not in the list of Global Themes Section.

**Steps to Reproduce**
1. Extract the tar.xz right away when downloaded. 
2. THERE SHOULD BE A FOLDER ON WHERE GLOBAL THEMES ARE STORED

**Expected behavior**
1. Once downloaded, it should properly extract right away into the path of Global Themes somewhere in the system 
2. If there is such a folder for this. It should be included in the system settings to redirect the user into that folder specifically so it would be much easier to download and extract themes outside the global theme store. 

**Screenshots**
//Herein is the installing or downloading process 
![image](https://user-images.githubusercontent.com/74012129/98268498-8f6a6680-1fc7-11eb-86ec-4fa5d5d40188.png)

//Herein is a screen shot of error prompt msg
![image](https://user-images.githubusercontent.com/74012129/98268700-cf314e00-1fc7-11eb-80bd-a96d8b24d753.png)

**Comment by dominichayesferen** [comment] 2020-11-09 03:22
Duplicate of #159, likely.

**Closed** 2020-11-09 03:22 UTC
Labels: Duplicate
