### ISSUE TITLE
Nemo configuration

### ISSUE THREAD

**Issue by jallain9** [feren-OS/Bug-Reporting-Center#102] opened 2020-01-12 00:29 UTC
I go to the File, Preferences, Behavior menu of Nemo. I select the option to open files with one click. From then on I can open files with one click. However, if I log out and then log back in the option has reverted to double-click. It does not remain on what I slected, single click to open files. I am using the Ubuntu Unitiy layout if it makes a difference.

**Comment by Sadi58** [comment] 2020-01-12 04:54
System Settings -> Workspace Behaviour
https://github.com/feren-OS/Bug-Reporting-Center/issues/97

**Comment by feren** [comment] 2020-01-12 17:34
This is a duplicate of #97

**Closed by feren** 2020-01-12 17:34 UTC
