### ISSUE TITLE
Problems running plasma wayland

### ISSUE THREAD

**Issue by dancaer69** [feren-OS/Bug-Reporting-Center#126] opened 2020-03-04 18:26 UTC
**Package Name or Section of Feren OS where this bug resides**
plasma shell wayland

**Describe the bug**
When run plasma wayland session there are issues as:
1. Settings application crash
2. Files application(probably all gtk apps) don't have window decorations
3. Applications use with admin priveleges (e.g Login manager) don't work. I put the password but don't open.

**Additional context**
I don't know if the above are bugs or need to install some more packages. The wayland session wasn't installed and I installed plasma-workspace-wayland package and all available kwin plugins except fbdev plugin.

**Comment by dancaer69** [comment] 2020-03-05 09:51
-Settings application crash happens with feren layouts. When I switched to Breeze theme, using kcmshell5 from command line to access theme subcategory, worked without problems. Also latte-dock has some problems and crashes when trying to change its settings.
-Windows decorations still not working(I tried to change theme for Gtk2/Gtk3 apps) for gtk apps. I tried nemo and geany. Some others which I think are gtk, as grisbi appear fine though.

**Comment by feren** [comment] 2020-03-06 23:46
Wayland on Feren OS, due to how early and WIP Plasma on Wayland is, is NOT recommended and NOT tested in Feren OS in the slightest. Feren OS currently IS NOT designed around Wayland's restrictions, meaning stuff like Update Manager, Software Sources, etc will out-right cease to function properly, if at all, under Wayland currently. I'm slowly starting to get stuff to work under Wayland, with Web Browser Manager having recently become all userland GUI-wise to be fine under Wayland, but even then that's not anywhere near being able to say using Feren OS on Wayland is sane.

That being said, here's the responses for your issues:
1. That's an upstream issue with the version of Kvantum that Feren OS uses. I do need to get Kvantum updated, but I just need to first find an up-to-date Kvantum source and then implement it into my automated software repository syncing script. CONFIRMED
2. That's an upstream Plasma Wayland issue - you should report it to them at bugs.kde.org if it is not already reported - I've seen people reporting it on OSs with Plasma on Wayland that aren't Feren OS. CONFIRMED UPSTREAM
3. Applications out-right cannot run graphically as Root under Wayland. That's entirely by design. WONTFIX

**Comment by feren** [comment] 2020-03-06 23:47
For now, I'll close this issue, but feel free to reopen this issue in a few years or so when Plasma on Wayland isn't such a massive work-in-progress project.

**Closed by feren** 2020-03-06 23:47 UTC
Labels: Untested Modifications
